# Generated by Django 2.0.7 on 2018-08-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
